[tool.poetry]
name = "cli-tools"
version = "0.1.0"
description = "A collection of CLI tools."
authors = ["Gemini"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.scripts]
cli = "cli_tools.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
